/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.plugin.git.tag;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'gradle.plugin.git.tag.greeting' plugin.
 */
class GradleGitTagPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("gradle.plugin.git.tag.gitTask");

        // Verify the result
        assertNotNull(project.getTasks().findByName("gitTask"));
    }
}
